typography_spectrum: 0.22100823698565364
color:
  brandStrength: 0.8667519798036665
  lightness: 0.5770401011686772
  saturation: 0.023864030139520764
  rhythmicContrast: 0.16502217925153673
  brandColors:
    - '#04BFBF'
    - '#CAFCD8'
    - '#F7E967'
    - '#A9CF54'
    - '#588F27'
opengraph:
  type: page
  appId: Vaitsa Schools
layout_spectrum: 0.3344913574401289
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/64c877b6-b91d-49eb-a130-b7a7ba64015c.jpg
name: Vaitsa &nbsp;Schools for Languages
navigation:
  - name: ΠΤΥΧΙΑ
    id: 81d07acd-5b75-4de8-9a2e-e2ade6af2f27
    type: content
  - name: 'Πρόσβαση '
    id: e18b5990-7656-4c46-9caa-80521bb9b5f0
    type: content
  - name: Φιλοσοφία Εκπαίδευσης
    id: 93c2cd5a-fae5-465a-a122-7c7ae19bb3e5
    type: content
  - name: Καλώς ήρθατε στα Vaitsa Schools
    id: 82420862-0139-4303-9dcb-749a2218cd42
    type: content
  - name: Προσφορές
    id: 7f4755e6-e0ed-452e-ab0e-1bf6c80925d3
    type: content
  - name: 'Κανονισμός λειτουργίας '
    id: 6db5067c-14f8-49ae-8a3c-e472e8fb09cd
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4068f455-926f-4d36-9ce2-66fa13c6aca1.jpg
title: 'Μιλήστε τη γλώσσα της επιτυχίας   '
coverPrefs:
  filter: false
description: Ξένες γλώσσες για μαθητές και ενήλικες
