layout_spectrum: 0.2671521796479748
typography_spectrum: 0.5882217410649403
color:
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  brandStrength: 0.9079363309847431
  lightness: 0.3581628345455605
  saturation: 0.6060443583862063
  rhythmicContrast: 0.00952890872872333
content_rating:
  adult: false
github: true
opengraph:
  type: page
  appId: '@vaitsaschools.gr'
analytics:
  facebook: '1309529282507698, 1894375410842122'
  google: UA-97991930-1
author:
  name: sotiris
  email: sotiris.koutsomitros@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/64c877b6-b91d-49eb-a130-b7a7ba64015c.jpg
name: Vaitsa Schools for Languages
navigation:
  - name: Φιλοσοφία Εκπαίδευσης
    id: 93c2cd5a-fae5-465a-a122-7c7ae19bb3e5
    type: content
  - name: PROFILE – Ποιοι είμαστε
    id: c4559889-e2ac-40a9-8458-8cf8e75d4f13
    type: content
  - name: Προσφορές - Offers
    id: 7f4755e6-e0ed-452e-ab0e-1bf6c80925d3
    type: content
  - name: Ξένες Γλώσσες για Ενήλικες
    id: ed73a28b-4335-4884-98fe-67b05736449f
    type: content
  - name: Που θα μας βρείτε?
    id: 52468244-996e-4b7d-bc39-f05cb84c06e5
    type: content
  - name: Επιτυχίες
    id: 0a39936b-b20a-4a2a-8a5a-6b2816f4bcb7
    type: content
  - name: ΠΤΥΧΙΑ Ξένων Γλωσσών
    id: 81d07acd-5b75-4de8-9a2e-e2ade6af2f27
    type: content
  - name: 'Κανονισμός λειτουργίας '
    id: 6db5067c-14f8-49ae-8a3c-e472e8fb09cd
    type: content
  - name: Οδηγίες για τις εξετάσεις Lower & Proficiency
    id: 210dc499-aeb3-41a4-b048-7b2644cab8cd
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0d32dc6c-ddcb-4311-8143-755eea2aed9e.jpg
title: Vaitsa Schools for Languages
content: []
description: >-
  Φροντίζουμε τον κάθε μαθητή ξεχωριστά μέσα στην ομάδα!   Η εμπειρία μας, η
  οργάνωση, οι υπέροχοι καθηγητές και τα ολιγομελή τμήματα είναι τα
  πλεονεκτήματα μας. Μαθήματα Αγγλικών, Γαλλικών, Γερμανικών, Ιταλικών,
  Ισπανικών για μαθητές και ενήλικες.
purpose: []
