name: Vaitsa Schools for Languages
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0d32dc6c-ddcb-4311-8143-755eea2aed9e.jpg
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/64c877b6-b91d-49eb-a130-b7a7ba64015c.jpg
layout_spectrum: 0.8920339327684539
typography_spectrum: 0.5832638447580508
analytics:
  facebook: '1894375410842122'
  google: UA-97991930-1
opengraph:
  type: page
  appId: '@vaitsaschools.gr'
color:
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  brandStrength: 0.5456438584106578
  lightness: 0.6366382217423825
  saturation: 0.5262489374863482
  rhythmicContrast: 0.45900291410818844
purpose:
  - type: external
    label: Σύνδεση στο ψηφιακό σχολείο
    url: 'http://portal.vaitsaschools.eu'
  - type: contact
    label: Contact me
    url: 'mailto:info@vaitsa.gr'
title: 'Καλώς ήρθατε στα Vaitsa Schools '
description: >-
  Ξένες γλώσσες για μαθητές και ενήλικες. Φροντίζουμε τον κάθε μαθητή ξεχωριστά
  μέσα στην ομάδα!
author:
  name: sotiris
  email: sotiris.koutsomitros@gmail.com
content_rating:
  adult: false
navigation:
  - name: PROFILE – Ποιοι είμαστε
    id: c4559889-e2ac-40a9-8458-8cf8e75d4f13
    type: content
  - name: Φιλοσοφία Εκπαίδευσης
    id: 93c2cd5a-fae5-465a-a122-7c7ae19bb3e5
    type: content
  - name: Προσφορές - Offers
    id: 7f4755e6-e0ed-452e-ab0e-1bf6c80925d3
    type: content
  - name: Επιτυχίες
    id: 0a39936b-b20a-4a2a-8a5a-6b2816f4bcb7
    type: content
  - name: ΠΤΥΧΙΑ
    id: 81d07acd-5b75-4de8-9a2e-e2ade6af2f27
    type: content
  - name: Οδηγίες για τις εξετάσεις Lower & Proficiency
    id: 210dc499-aeb3-41a4-b048-7b2644cab8cd
    type: content
  - name: 'Κανονισμός λειτουργίας '
    id: 6db5067c-14f8-49ae-8a3c-e472e8fb09cd
    type: content
  - name: Portal
    url: 'http://portal.vaitsaschools.gr'
    type: external
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/33c734fa-d455-49eb-99d3-0014586f5e40.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/33c734fa-d455-49eb-99d3-0014586f5e40.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
