layout_spectrum: 0.1834769246634096
typography_spectrum: 0.4304841021075845
color:
  brandStrength: 0.8667519798036665
  lightness: 0.5770401011686772
  saturation: 0.023864030139520764
  rhythmicContrast: 0.16502217925153673
  brandColors:
    - '#04BFBF'
    - '#CAFCD8'
    - '#F7E967'
    - '#A9CF54'
    - '#588F27'
coverPrefs:
  filter: false
opengraph:
  type: page
  appId: Vaitsa Schools
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/64c877b6-b91d-49eb-a130-b7a7ba64015c.jpg
name: Vaitsa &nbsp;Schools for Languages
navigation:
  - name: PROFILE – Ποιοι είμαστε
    id: c4559889-e2ac-40a9-8458-8cf8e75d4f13
    type: content
  - name: Φιλοσοφία Εκπαίδευσης
    id: 93c2cd5a-fae5-465a-a122-7c7ae19bb3e5
    type: content
  - name: ΠΤΥΧΙΑ
    id: 81d07acd-5b75-4de8-9a2e-e2ade6af2f27
    type: content
  - name: 'Κανονισμός λειτουργίας '
    id: 6db5067c-14f8-49ae-8a3c-e472e8fb09cd
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4068f455-926f-4d36-9ce2-66fa13c6aca1.jpg
title: 'Μιλήστε τη γλώσσα της επιτυχίας   '
description: Ξένες γλώσσες για μαθητές και ενήλικες
